### ISSUE TITLE
프로젝트 초기 파일 업로드

### ISSUE THREAD

**Issue by effort-type** [effort-type/OOD-SpringBootVersion#1]
## 📝 Description
프로젝트 파일 업로드

## 📍 Todo
- [x] 프로젝트 파일 업로드
- [x] Issues 템플릿 적용
- [x] Pull requests 템플릿 적용
- [x] Labels 생성
