### ISSUE TITLE
JSTL 코드 추가

### ISSUE THREAD

**Issue by effort-type** [effort-type/OOD-SpringBootVersion#11]
## 📝 Description
5장 기존 코드를 JSTL (JavaServer Pages Standard Tag Library) 코드로 수정

## 📍 Todo
- [x] deu.se.ood.ch04.SumBean.java 로그 부분 @Slf4j 어노테이션 사용하도록 수정
- [x] View 파일 생성 및 구현
- [x] 5장 Controller에 추가
- [x] JSTL을 사용해서 스크립틀릿(자바 코드) if문 제거하기
- [x] JSTL을 사용해서 스크립틀릿(자바 코드) for문 제거하기
- [x] URL Test Project 실습
