### ISSUE TITLE
DB 연결

### ISSUE THREAD

**Issue by effort-type** [effort-type/OOD-SpringBootVersion#20]
## 📝 Description
docker container에 mysql를 설치 후 mysql workbench로 접속하도록 환경 설정

## 📍 Todo
- [x] docker 설치
- [x] docker 내부 DB 설치
- [x] docker DB와 connection
- [x] DB 연결을 위한 의존성 추가
- [x] 서버 관련 민감한 정보 파일은 gitignore 파일에 등록
