### ISSUE TITLE
DB 

### ISSUE THREAD

**Issue by effort-type** [effort-type/OOD-SpringBootVersion#21]
## 📝 Description
6장 스프링부트 실습 코드 추가

## 📍 Todo
- [x] controller 구현
- [x] view 구현
- [x] DB 드라이버 의존성 추가
- [x] README 파일 업데이트
- [x] tag 파일 구현
- [x] HikariCP를 사용한 DB 사용 방법 코드 구현
- [x] 6장 DB 스프링 부트 코드 모두 실습해보기
